# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'file_load/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lddfile', models.FileField(upload_to=b'Files/%Y/%m/%d')),
            ],
        ),
    ]
